In [1]:
!dir

 Volume in drive C is Windows
 Volume Serial Number is B233-0680

 Directory of C:\data science\Reccomender System

02-04-2024  20:19    <DIR>          .
01-04-2024  15:59    <DIR>          ..
02-04-2024  20:19    <DIR>          .ipynb_checkpoints
02-04-2024  15:13         2,800,972 cleaned_metadata.csv
02-04-2024  16:06           821,468 IMDB_series_data.csv.xls
01-04-2024  15:51        34,445,126 movies_metadata.csv.xls
02-04-2024  20:19                72 rec systrem.ipynb
02-04-2024  15:41           242,880 Working with Data (R S).ipynb
02-04-2024  16:05           245,658 Working with data.ipynb
               6 File(s)     38,556,176 bytes
               3 Dir(s)  184,482,885,632 bytes free

In [132]:
import pandas as pd 
import numpy as np

In [133]:
df = pd.read_csv("IMDB_series_data.csv.xls")

In [134]:
df

,Poster_Link,Series_Title,Runtime_of_Series,Certificate,Runtime_of_Episodes,Genre,IMDB_Rating,Overview,Star1,Star2,Star3,Star4,No_of_Votes
0,https://m.media-amazon.com/images/M/MV5BYTRiND...,Game of Thrones,(2011–2019),A,57 min,"Action, Adventure, Drama",9.3,Nine noble families fight for control over the...,Emilia Clarke,Peter Dinklage,Kit Harington,Lena Headey,1773458
1,https://m.media-amazon.com/images/M/MV5BMjhiMz...,Breaking Bad,(2008–2013),18,49 min,"Crime, Drama, Thriller",9.5,A high school chemistry teacher diagnosed with...,Bryan Cranston,Aaron Paul,Anna Gunn,Betsy Brandt,1468887
2,https://m.media-amazon.com/images/M/MV5BMTc5Zm...,The Walking Dead,(2010– ),18+,44 min,"Drama, Horror, Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a com...,Andrew Lincoln,Norman Reedus,Melissa McBride,Danai Gurira,854698
3,https://m.media-amazon.com/images/M/MV5BNDVkYj...,Friends,(1994–2004),13+,22 min,"Comedy, Romance",8.9,Follows the personal and professional lives of...,Jennifer Aniston,Courteney Cox,Lisa Kudrow,Matt LeBlanc,829816
4,https://m.media-amazon.com/images/M/MV5BMjEzMD...,Stranger Things,(2016– ),15,51 min,"Drama, Fantasy, Horror",8.7,"When a young boy disappears, his mother, a pol...",Millie Bobby Brown,Finn Wolfhard,Winona Ryder,David Harbour,824966
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,https://m.media-amazon.com/images/M/MV5BYTk4OG...,Shaman Kingu,(2001–2005),NaN,23 min,"Animation, Action, Adventure",8.1,SHAMAN KING follows the adventures of a 13-yea...,Oliver Wyman,Andrew Rannells,Michael Sinterniklaas,Megumi Hayashibara,5131
1996,https://m.media-amazon.com/images/M/MV5BMTUyND...,"Eerie, Indiana",(1991–1992),NaN,30 min,"Adventure, Comedy, Drama",8.2,Teenage weirdness investigator Marshall Teller...,Omri Katz,Justin Shenkarow,Mary-Margaret Humes,Francis Guinan,5128
1997,https://m.media-amazon.com/images/M/MV5BMTcxMD...,Gunsmoke,(1955–1975),NaN,60 min,Western,7.9,Marshal Matt Dillon keeps the peace in rough a...,James Arness,Milburn Stone,Amanda Blake,Ken Curtis,5115
1998,https://m.media-amazon.com/images/M/MV5BYWQwNm...,The Cheat,(2017– ),NaN,20 min,"Action, Drama, Sci-Fi",8.8,Felix is a software developer who works for th...,Taha Ulukaya,Taner Sahin,Andac Ulukaya,Neslihan Ulusoy,5111
1999,https://m.media-amazon.com/images/M/MV5BMjQ5Mj...,Comic Book Men,(2012–2018),NaN,22 min,"Comedy, Reality-TV",7.7,An unscripted series set in Smith's iconic com...,Kevin Smith,Walter Flanagan,Mike Zapcic,Bryan Johnson,5109

In [135]:
df["Runtime_of_Series"].unique()

array(['(2011–2019)', '(2008–2013)', '(2010– )', '(1994–2004)',
       '(2016– )', '(2010–2017)', '(2007–2019)', '(2006–2021)',
       '(2005–2014)', '(2014– )', '(2004–2010)', '(2005–2017)',
       '(2013–2018)', '(2011– )', '(2013–2020)', '(2005–2013)',
       '(2004–2012)', '(2012–2020)', '(2005–2020)', '(2013– )',
       '(1989– )', '(2015–2018)', '(2015–2017)', '(2009–2020)',
       '(2015–2019)', '(1997– )', '(2015–2021)', '(2011–2020)',
       '(1999– )', '(1999–2007)', '(2019– )', '(2017– )', '(2002–2008)',
       '(2017–2020)', '(2009–2017)', '(2013–2019)', '(2003–2019)',
       '(2008–2014)', '(1989–1998)', '(2005– )', '(2005–2008)',
       '(2002–2003)', '(2003–2015)', '(2006–2007)', '(2001–2010)',
       '(II) (2006–2010)', '(2013–2015)', '(2013–2022)', '(2010–2013)',
       '(2009–2015)', '(2017–2019)', '(2014–2020)', '(1999–2013)',
       '(2014–2019)', '(2011–2018)', '(2007–2015)', '(2011–2021)',
       '(1993–2018)', '(1990–1991)', '(2010–2014)', '(2007–2014)',
       '(2008– )', '(2010–2015)', '(2011–2016)', '(2004–2011)',
       '(2005–2007)', '(2007–2012)', '(1998–2006)', '(2004–2009)',
       '(2018– )', '(2018–2020)', '(2009–2016)', '(2009– )',
       '(2006–2013)', '(1997–2003)', '(1999–2000)', '(2011–2017)',
       '(2009–2012)', '(1990–1996)', '(2010–2019)', '(2001–2005)',
       '(2003– )', '(2009–2014)', '(2000–2006)', '(2016–2018)',
       '(2015– )', '(2001–2011)', '(2016–2020)', '(2017–2018)',
       '(1996–2003)', '(2011–2015)', '(2014–2016)', '(2009–2011)',
       '(2002– )', '(1998–2004)', '(2012–2014)', '(2000– )',
       '(1990–1995)', '(2005–2012)', '(1987–1994)', '(2016–2019)',
       '(2013–2017)', '(2000–2007)', '(2012–2019)', '(2001–2003)',
       '(2011–2014)', '(1987–1997)', '(2005–2009)', '(2004–2006)',
       '-2018', '(2009–2013)', '(2014–2017)', '(1998–1999)',
       '(1992–1995)', '(2013–2016)', '-2020', '(2006–2014)',
       '(1975–1979)', '(2007–2017)', '(I) (2013–2016)', '(1997–2007)',
       '(2003–2007)', '(2008–2010)', '-2011', '(2000–2015)',
       '(2010–2018)', '(1998–2007)', '(2018–2019)', '(2007–2013)',
       '(2012–2016)', '(1993–2004)', '(2008–2012)', '(1966–1969)',
       '(2015–2016)', '(2003–2012)', '(1959–1964)', '(2002–2007)',
       '(2015–2020)', '(2007–2010)', '(1989–1996)', '(1969–1974)',
       '(2020– )', '(2004–2019)', '(2012–2018)', '(2010–2020)',
       '(I) (2018– )', '(2002–2009)', '(2012–2017)', '(1999–2006)',
       '(1999–2004)', '(1996– )', '(2008–2020)', '(2003–2004)',
       '(2017–2021)', '(1995–2001)', '(2009–2010)', '(I) (2012–2015)',
       '(2008–2009)', '-2017', '(2006–2011)', '(2007–2009)',
       '(2003–2006)', '(2000–2004)', '(2014–2018)', '(2016–2017)',
       '(2006–2008)', '(2002–2012)', '(1995–2003)', '(2021– )',
       '(1993–1999)', '(2014–2015)', '(1987–1995)', '(2003–2010)',
       '(I) (2019– )', '(II) (2017– )', '(2006–2012)', '(1998–2020)',
       '(1995–1996)', '(1994–2009)', '(1999–2001)', '(1972–1983)',
       '(2010–2011)', '-1989', '(2011–2013)', '(1982–1993)',
       '(1986–1989)', '(2013–2014)', '(1996–2001)', '(1981–2003)',
       '(2001–2017)', '(1997–2010)', '(2001–2006)', '(2011–2012)',
       '(2009–2018)', '(I) (2009–2015)', '(2004–2013)', '-1986',
       '(1975– )', '(2005–2010)', '(2004–2008)', '(2003–2005)',
       '(2004–2007)', '(2012–2013)', '(I) (2013–2014)', '(2001–2004)',
       '-1987', '(2004–2005)', '(1991–1999)', '(2006–2010)',
       '(I) (2014–2020)', '(1988–2018)', '(1993–2000)', '(2012– )',
       '-2012', '(1989–2013)', '(1999–2002)', '(1992–1997)',
       '(2001–2018)', '(1998–2005)', '-2014', '(1995–1998)',
       '(1998–2003)', '(1982–1983)', '(1985–1992)', '(1963–1989)',
       '(1983–1987)', '(1988–1993)', '(2001–2009)', '(1999–2003)',
       '(1999–2008)', '(1960–1966)', '(1997–2004)', '(1988– )',
       '(I) (2007–2009)', '(1989–1992)', '(1990–2006)', '(1990–2010)',
       '(1986–1990)', '(1984–1992)', '(1990–2000)', '(1960–1975)',
       '(2000–2002)', '(1987–1996)', '(1996–2004)', '(1997–2002)',
       '(1982–1986)', '(1969–1970)', '(2010–2012)', '(2010–2016)',
       '(1987–1990)', '(1997–1998)', '(2013–2021)', '(1971–2003)',
       '(1993–1998)', '(2006–2009)', '-2019', '(1993–2011)',
       '(1995–1999)', '(1994–1998)', '(2006– )', '(1996–2002)',
       '(1989–1993)', '(2003–2008)', '(2005–2011)', '-2009',
       '(1989–2001)', '(1978–2002)', '(I) (2004–2009)', '(1996–2007)',
       '(2002–2005)', '(1982–1992)', '(2003–2018)', '(2007–2008)',
       '(2007–2011)', '(1984–1989)', '(1997–2001)', '-2016',
       '(1988–1999)', '(1976–1981)', '(1980–1988)', '-2015',
       '(1951–1957)', '(2006–2020)', '(1993–1997)', '(1992–2019)',
       '(I) (2012–2013)', '(II) (2020– )', '(2019–2020)', '(1991–1996)',
       '(2001–2007)', '(2009–2019)', '(1984–1987)', '(I) (2017– )',
       '(1993–1996)', '(1984–1985)', '(2012–2015)', '-1998',
       '(2008–2011)', '(1994–1995)', '(1966–1968)', '(1983–1986)',
       '(2004–2018)', '(2000–2005)', '(1984–1996)', '(1962–1963)',
       '(I) (2000–2006)', '(1997–1999)', '(1974–1983)', '(1985–1989)',
       '(1992–2012)', '(2002–2006)', '(1991–1994)', '(1996–1999)',
       '(1964–1972)', '(II) (2020–2021)', '(1988–1990)', '(1993–2009)',
       '(1991–1992)', '(1995–2000)', '(1995–2005)', '(1974–1984)',
       '(1983–1985)', '(1995–2004)', '(1982–1989)', '(1969–2011)',
       '(1981–1989)', '-1982', '(2008–2015)', '(1998–2001)',
       '(1985–1986)', '(2008–2021)', '(1993–2001)', '(I) (2019)',
       '(2014–2021)', '(2004–2017)', '(1955–1962)', '(1996–2000)',
       '(1964–1966)', '(2002–2011)', '(1994–1996)', '(1987–1988)',
       '(1971–1979)', '(1992–1998)', '(2004– )', '(1978–1979)', '-2007',
       '(2000–2003)', '(2001– )', '(1982–1984)', '(1965–1970)',
       '(2020–2021)', '(1964–1967)', '(2008–2016)', '(1993–2015)',
       '(1991–1998)', '(2002–2015)', '(1980–1984)', '-2006',
       '(1967–1968)', '(1976–1984)', '(1960–1968)', '(1978–1991)',
       '(2007–2020)', '(1969– )', '-2004', '(1994–2020)', '(2000–2001)',
       '(1977–1982)', '(2005–2006)', '-2010', '(1993–2005)',
       '(1995–1997)', '(1991–1995)', '(1990–1993)', '(I) (2016)',
       '(1978–1983)', '(1979–1985)', '(2001–2015)', '(II) (2015–2018)',
       '(1995–2002)', '(1994–1999)', '(1992–1999)', '(1987–1991)',
       '(1990–1997)', '(2006–2015)', '(1986–1988)', '(1998–2002)',
       '(1994–1997)', '(2005–2015)', '(2007– )', '(2002–2019)', '-1981',
       '(1987–2000)', '(1999–2017)', '(1960–1962)', '(1984–1986)',
       '(1988–1995)', '(1992–2014)', '(I) (1996–1999)', '(1978–1982)',
       '(1995–2016)', '(2007–2016)', '(1986–1987)', '(1985–1991)',
       '(II) (2000– )', '(1978–1986)', '(II) (2007– )', '(1974–1978)',
       '(1968–1978)', '(1994–2000)', '(I) (2005– )', '(1961–1988)',
       '(1966–1973)', '(1977–1987)', '(1999–2005)', '(1992–1996)',
       '(2001–2014)', '(2003–2009)', '(1961–1966)', '-2021',
       '(2000–2011)', '(1965–1971)', '(1986–1991)', '-2008',
       '(1986–1993)', '(1988–2021)', '(2001–2002)', '(I) (2006– )',
       '(1993– )', '(1977–1983)', '(1962–1971)', '(II) (2012– )',
       '(1959–1973)', '(1975–1977)', '(1972–1977)', '(1993–1994)',
       '(1977–1986)', '(1979–1981)', '(1975–1985)', '(1992–1993)',
       '(II) (2010– )', '(1985– )', '(1968–2001)', '(1994–2001)', '-2013',
       '(I) (2016–2017)', '(1982–1987)', '(1981–1987)', '(1998–2000)',
       '(1963–1965)', '(1972–1985)', '(1987– )', '(1970–1977)',
       '(2005–2018)', '(1974–1980)', '(1961–1962)', '(1994–2019)',
       '(1977–1984)', '(1961–1969)', '(I) (2016–2018)', '(1957–1963)',
       '(1973–1978)', '(1965–1968)', '(1989–1991)', '(1997–2016)',
       '(1998–2012)', '(1986–1995)', '(1976–1983)', '(1992–2010)',
       '(1981–1986)', '(1979–1984)', '(I) (2001–2012)', '(1994–2003)',
       '(1976–1978)', '(I) (2020)', '(1992–2011)', '(1984– )', '(1965– )',
       '(2002–2014)', '(1979–1988)', '(1968–1970)', '(1973–1975)',
       '(1989–1997)', '(1974–1979)', '(1977–1981)', '(1957– )',
       '(1983–1995)', '(2004–2020)', '(1980–2006)', '(1982–1990)',
       '(1972–1981)', '(1968–1980)', '(1987–1993)', '(I) (2017)',
       '(1990–2001)', '(2000–2009)', '(1999–2010)', '(1968–1977)',
       '(1983–1988)', '(1973– )', '(2004–2014)', '(2000–2019)',
       '(1974–1977)', '(1989–2020)', '(1984–1990)', '(I) (2018)',
       '(1970–1975)', '(1988–1998)', '(1972–1975)', '-2001',
       '(1996–2015)', '(1957–1966)', '(1985–1987)', '(1955–1975)'],
      dtype=object)

In [136]:
df.columns

Index(['Poster_Link', 'Series_Title', 'Runtime_of_Series', 'Certificate',
       'Runtime_of_Episodes', 'Genre', 'IMDB_Rating', 'Overview', 'Star1',
       'Star2', 'Star3', 'Star4', 'No_of_Votes'],
      dtype='object')

Knowledge Based recommender

In [137]:
df2 = df[["Series_Title","Runtime_of_Series","Runtime_of_Episodes","Certificate","Genre","IMDB_Rating","No_of_Votes"]]

In [138]:
df2

,Series_Title,Runtime_of_Series,Runtime_of_Episodes,Certificate,Genre,IMDB_Rating,No_of_Votes
0,Game of Thrones,(2011–2019),57 min,A,"Action, Adventure, Drama",9.3,1773458
1,Breaking Bad,(2008–2013),49 min,18,"Crime, Drama, Thriller",9.5,1468887
2,The Walking Dead,(2010– ),44 min,18+,"Drama, Horror, Thriller",8.2,854698
3,Friends,(1994–2004),22 min,13+,"Comedy, Romance",8.9,829816
4,Stranger Things,(2016– ),51 min,15,"Drama, Fantasy, Horror",8.7,824966
...,...,...,...,...,...,...,...
1995,Shaman Kingu,(2001–2005),23 min,NaN,"Animation, Action, Adventure",8.1,5131
1996,"Eerie, Indiana",(1991–1992),30 min,NaN,"Adventure, Comedy, Drama",8.2,5128
1997,Gunsmoke,(1955–1975),60 min,NaN,Western,7.9,5115
1998,The Cheat,(2017– ),20 min,NaN,"Action, Drama, Sci-Fi",8.8,5111
1999,Comic Book Men,(2012–2018),22 min,NaN,"Comedy, Reality-TV",7.7,5109

In [139]:
df2.dtypes

Series_Title            object
Runtime_of_Series       object
Runtime_of_Episodes     object
Certificate             object
Genre                   object
IMDB_Rating            float64
No_of_Votes              int64
dtype: object

In [140]:
df2

,Series_Title,Runtime_of_Series,Runtime_of_Episodes,Certificate,Genre,IMDB_Rating,No_of_Votes
0,Game of Thrones,(2011–2019),57 min,A,"Action, Adventure, Drama",9.3,1773458
1,Breaking Bad,(2008–2013),49 min,18,"Crime, Drama, Thriller",9.5,1468887
2,The Walking Dead,(2010– ),44 min,18+,"Drama, Horror, Thriller",8.2,854698
3,Friends,(1994–2004),22 min,13+,"Comedy, Romance",8.9,829816
4,Stranger Things,(2016– ),51 min,15,"Drama, Fantasy, Horror",8.7,824966
...,...,...,...,...,...,...,...
1995,Shaman Kingu,(2001–2005),23 min,NaN,"Animation, Action, Adventure",8.1,5131
1996,"Eerie, Indiana",(1991–1992),30 min,NaN,"Adventure, Comedy, Drama",8.2,5128
1997,Gunsmoke,(1955–1975),60 min,NaN,Western,7.9,5115
1998,The Cheat,(2017– ),20 min,NaN,"Action, Drama, Sci-Fi",8.8,5111
1999,Comic Book Men,(2012–2018),22 min,NaN,"Comedy, Reality-TV",7.7,5109

In [141]:
import re

In [142]:
def clean_date_range(date_range):
    #removing symbols
    cleaned_range = re.sub(r'[\(\)–\s]', '', date_range)
    #spliting to start and end year
    start_year = cleaned_range[:4]
    end_year = cleaned_range[4:]
    if end_year == '':
        end_year = 'Present'
    return f"{start_year}-{end_year}"

In [143]:
cleaned_array = [clean_date_range(date_range) for date_range in df2["Runtime_of_Series"]]

In [144]:
type(cleaned_array)

list

In [145]:
df2["Runtime_of_Series"] = cleaned_array

C:\Users\91994\AppData\Local\Temp\ipykernel_36076\3239963980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Runtime_of_Series"] = cleaned_array

In [146]:
df2

,Series_Title,Runtime_of_Series,Runtime_of_Episodes,Certificate,Genre,IMDB_Rating,No_of_Votes
0,Game of Thrones,2011-2019,57 min,A,"Action, Adventure, Drama",9.3,1773458
1,Breaking Bad,2008-2013,49 min,18,"Crime, Drama, Thriller",9.5,1468887
2,The Walking Dead,2010-Present,44 min,18+,"Drama, Horror, Thriller",8.2,854698
3,Friends,1994-2004,22 min,13+,"Comedy, Romance",8.9,829816
4,Stranger Things,2016-Present,51 min,15,"Drama, Fantasy, Horror",8.7,824966
...,...,...,...,...,...,...,...
1995,Shaman Kingu,2001-2005,23 min,NaN,"Animation, Action, Adventure",8.1,5131
1996,"Eerie, Indiana",1991-1992,30 min,NaN,"Adventure, Comedy, Drama",8.2,5128
1997,Gunsmoke,1955-1975,60 min,NaN,Western,7.9,5115
1998,The Cheat,2017-Present,20 min,NaN,"Action, Drama, Sci-Fi",8.8,5111
1999,Comic Book Men,2012-2018,22 min,NaN,"Comedy, Reality-TV",7.7,5109

In [120]:
# df2["vote_avg"] = df2["No_of_Votes"].mean()

C:\Users\91994\AppData\Local\Temp\ipykernel_36076\3549475580.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["vote_avg"] = df2["No_of_Votes"].mean()

In [121]:
df2

,Series_Title,Runtime_of_Series,Runtime_of_Episodes,Certificate,Genre,IMDB_Rating,No_of_Votes,vote_avg
0,Game of Thrones,2011-2019,57 min,A,"Action, Adventure, Drama",9.3,1773458,37703.9065
1,Breaking Bad,2008-2013,49 min,18,"Crime, Drama, Thriller",9.5,1468887,37703.9065
2,The Walking Dead,2010-Present,44 min,18+,"Drama, Horror, Thriller",8.2,854698,37703.9065
3,Friends,1994-2004,22 min,13+,"Comedy, Romance",8.9,829816,37703.9065
4,Stranger Things,2016-Present,51 min,15,"Drama, Fantasy, Horror",8.7,824966,37703.9065
...,...,...,...,...,...,...,...,...
1995,Shaman Kingu,2001-2005,23 min,NaN,"Animation, Action, Adventure",8.1,5131,37703.9065
1996,"Eerie, Indiana",1991-1992,30 min,NaN,"Adventure, Comedy, Drama",8.2,5128,37703.9065
1997,Gunsmoke,1955-1975,60 min,NaN,Western,7.9,5115,37703.9065
1998,The Cheat,2017-Present,20 min,NaN,"Action, Drama, Sci-Fi",8.8,5111,37703.9065
1999,Comic Book Men,2012-2018,22 min,NaN,"Comedy, Reality-TV",7.7,5109,37703.9065

In [148]:
df2['Genre'] = df2['Genre'].fillna('[]')

C:\Users\91994\AppData\Local\Temp\ipykernel_36076\1284317396.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Genre'] = df2['Genre'].fillna('[]')

In [124]:
df2

,Series_Title,Runtime_of_Series,Runtime_of_Episodes,Certificate,Genre,IMDB_Rating,No_of_Votes
0,Game of Thrones,2011-2019,57 min,A,"Action, Adventure, Drama",9.3,1773458
1,Breaking Bad,2008-2013,49 min,18,"Crime, Drama, Thriller",9.5,1468887
2,The Walking Dead,2010-Present,44 min,18+,"Drama, Horror, Thriller",8.2,854698
3,Friends,1994-2004,22 min,13+,"Comedy, Romance",8.9,829816
4,Stranger Things,2016-Present,51 min,15,"Drama, Fantasy, Horror",8.7,824966
...,...,...,...,...,...,...,...
1995,Shaman Kingu,2001-2005,23 min,NaN,"Animation, Action, Adventure",8.1,5131
1996,"Eerie, Indiana",1991-1992,30 min,NaN,"Adventure, Comedy, Drama",8.2,5128
1997,Gunsmoke,1955-1975,60 min,NaN,Western,7.9,5115
1998,The Cheat,2017-Present,20 min,NaN,"Action, Drama, Sci-Fi",8.8,5111
1999,Comic Book Men,2012-2018,22 min,NaN,"Comedy, Reality-TV",7.7,5109

In [125]:
s = df2.apply(lambda x: pd.Series(x['Genre']),axis=1).stack().reset_index(level=1,drop=True)

In [126]:
s.name="Genre"

In [151]:
single_genre = s.str.split(', ').explode()

single_genre = single_genre.reset_index(drop=True)

In [152]:
df2["Genre"] = single_genre

C:\Users\91994\AppData\Local\Temp\ipykernel_36076\46045095.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Genre"] = single_genre

In [154]:
df2

,Series_Title,Runtime_of_Series,Runtime_of_Episodes,Certificate,Genre,IMDB_Rating,No_of_Votes
0,Game of Thrones,2011-2019,57 min,A,Action,9.3,1773458
1,Breaking Bad,2008-2013,49 min,18,Adventure,9.5,1468887
2,The Walking Dead,2010-Present,44 min,18+,Drama,8.2,854698
3,Friends,1994-2004,22 min,13+,Crime,8.9,829816
4,Stranger Things,2016-Present,51 min,15,Drama,8.7,824966
...,...,...,...,...,...,...,...
1995,Shaman Kingu,2001-2005,23 min,NaN,Drama,8.1,5131
1996,"Eerie, Indiana",1991-1992,30 min,NaN,Mystery,8.2,5128
1997,Gunsmoke,1955-1975,60 min,NaN,Animation,7.9,5115
1998,The Cheat,2017-Present,20 min,NaN,Action,8.8,5111
1999,Comic Book Men,2012-2018,22 min,NaN,Adventure,7.7,5109

In [155]:
df2["Genre"].fillna(df2["Genre"].mode()[0],inplace=True)

C:\Users\91994\AppData\Local\Temp\ipykernel_36076\2914621542.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Genre"].fillna(df2["Genre"].mode()[0],inplace=True)

In [157]:
df2["Certificate"].fillna(df2["Certificate"].mode()[0],inplace=True)

C:\Users\91994\AppData\Local\Temp\ipykernel_36076\4231345345.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Certificate"].fillna(df2["Certificate"].mode()[0],inplace=True)

In [170]:
df2["Release_year"] = df2["Runtime_of_Series"].apply(lambda x: str(x).split('-')[0] )

C:\Users\91994\AppData\Local\Temp\ipykernel_36076\2970625972.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Release_year"] = df2["Runtime_of_Series"].apply(lambda x: str(x).split('-')[0] )

In [172]:
df2

,Series_Title,Runtime_of_Series,Runtime_of_Episodes,Certificate,Genre,IMDB_Rating,No_of_Votes,Release_year
0,Game of Thrones,2011-2019,57 min,A,Action,9.3,1773458,2011
1,Breaking Bad,2008-2013,49 min,18,Adventure,9.5,1468887,2008
2,The Walking Dead,2010-Present,44 min,18+,Drama,8.2,854698,2010
3,Friends,1994-2004,22 min,13+,Crime,8.9,829816,1994
4,Stranger Things,2016-Present,51 min,15,Drama,8.7,824966,2016
...,...,...,...,...,...,...,...,...
1995,Shaman Kingu,2001-2005,23 min,18,Drama,8.1,5131,2001
1996,"Eerie, Indiana",1991-1992,30 min,18,Mystery,8.2,5128,1991
1997,Gunsmoke,1955-1975,60 min,18,Animation,7.9,5115,1955
1998,The Cheat,2017-Present,20 min,18,Action,8.8,5111,2017
1999,Comic Book Men,2012-2018,22 min,18,Adventure,7.7,5109,2012

In [176]:
df2["Release_year"].unique()

array(['2011', '2008', '2010', '1994', '2016', '2007', '2006', '2005',
       '2014', '2004', '2013', '2012', '1989', '2015', '2009', '1997',
       '1999', '2019', '2017', '2002', '2003', '2001', 'II20', '1993',
       '1990', '1998', '2018', '2000', '1996', '1987', '', '1992', '1975',
       'I201', '1966', '1959', '1969', '2020', '1995', '2021', '1972',
       '1982', '1986', '1981', 'I200', '1991', '1988', '1985', '1963',
       '1983', '1960', '1984', '1971', '1978', '1976', '1980', '1951',
       '1962', '1974', '1964', '1955', '1965', '1967', '1977', '1979',
       'I199', '1968', '1961', '1970', '1957', '1973', 'I202'],
      dtype=object)

In [171]:
df2["Certificate"].value_counts()

18           1528
16            133
16+            49
15+            45
A              42
13             42
18+            41
U              29
12+            18
7              16
UA             14
PG             13
13+             9
All             6
Not Rated       6
15              4
7+              3
R               2
Name: Certificate, dtype: int64

In [173]:
def buld_chart(df2,percentile=0.08):
    print("Preferred Genre: ")
    genre = input().capitalize()
    print("Preferred Certificate: ")
    certificate = str(input())
    print("Release Year)")
    year = str(input())
    movies=df2.copy()
    movies=movies[(movies["Genre"]==genre) & (movies["Certificate"]==certificate) & (movies["Release_year"]==year)]
    C = movies["IMDB_Rating"].mean()
    m = movies["No_of_Votes"].quantile(percentile)
    q_movies = movies.copy().loc[movies['No_of_Votes']>=m]
    q_movies['score'] = q_movies.apply(lambda x: (x['No_of_Votes']/(x['No_of_Votes']+m)* x['IMDB_Rating']) + (m/(m+x['No_of_Votes'])*C),axis=1)
    q_movies = q_movies.sort_values(by='score',ascending=False)
    return q_movies

In [174]:
buld_chart(df2).head()

Preferred Genre:

 Action

Preferred Certificate:

 18

Release Year)

 2008

,Series_Title,Runtime_of_Series,Runtime_of_Episodes,Certificate,Genre,IMDB_Rating,No_of_Votes,Release_year,score
752,The Secret Life of the American Teenager,2008-2013,43 min,18,Action,5.0,19182,2008,5.0